const express = require('express');
const cors = require('cors');
const path = require('path');
const { Pool } = require('pg');

const app = express();
const PORT = process.env.PORT || 5000;

// Supabase Transaction Pooler connection string.
// Set DATABASE_URL in Render. Never commit the database password to GitHub.
if (!process.env.DATABASE_URL) {
  console.error('ERROR: DATABASE_URL environment variable is missing.');
  process.exit(1);
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
  max: 5,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 10000
});

app.use(cors());
app.use(express.json());

// Serve the CRM frontend when deployed as one Render Web Service.
app.use(express.static(path.join(__dirname, '..', 'client')));

async function initDatabase() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS leads (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      company TEXT,
      phone TEXT NOT NULL,
      email TEXT,
      service TEXT,
      expected_value NUMERIC DEFAULT 0,
      status TEXT DEFAULT 'NEW'
    );

    CREATE TABLE IF NOT EXISTS clients (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      company TEXT,
      phone TEXT NOT NULL,
      email TEXT,
      gstin TEXT,
      state TEXT DEFAULT 'Maharashtra',
      state_code TEXT DEFAULT '27'
    );

    CREATE TABLE IF NOT EXISTS projects (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      client_name TEXT NOT NULL,
      service TEXT,
      budget NUMERIC DEFAULT 0,
      status TEXT DEFAULT 'IN_PROGRESS',
      deadline DATE
    );

    CREATE TABLE IF NOT EXISTS invoices (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      invoice_number TEXT UNIQUE,
      client_name TEXT NOT NULL,
      taxable_amount NUMERIC NOT NULL,
      gst_rate NUMERIC DEFAULT 18,
      total_tax NUMERIC NOT NULL,
      grand_total NUMERIC NOT NULL,
      status TEXT DEFAULT 'PENDING',
      date DATE
    );
  `);

  console.log('Supabase PostgreSQL tables are ready.');
}

// Health check
app.get('/api/health', async (req, res) => {
  try {
    await pool.query('SELECT 1');
    res.json({ success: true, database: 'connected' });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// DASHBOARD STATS
app.get('/api/stats', async (req, res) => {
  try {
    const { rows } = await pool.query(`
      SELECT
        (SELECT COUNT(*) FROM leads) AS total_leads,
        (SELECT COUNT(*) FROM clients) AS total_clients,
        (SELECT COUNT(*) FROM projects WHERE status = 'IN_PROGRESS') AS active_projects,
        (SELECT COALESCE(SUM(grand_total), 0) FROM invoices) AS total_revenue
    `);
    res.json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// LEADS
app.get('/api/leads', async (req, res) => {
  try {
    const { rows } = await pool.query('SELECT * FROM leads ORDER BY id DESC');
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/leads', async (req, res) => {
  try {
    const { name, company, phone, email, service, expected_value } = req.body;

    if (!name || !phone || !service) {
      return res.status(400).json({ error: 'Name, phone and service are required.' });
    }

    const { rows } = await pool.query(
      `INSERT INTO leads (name, company, phone, email, service, expected_value)
       VALUES ($1, $2, $3, $4, $5, $6)
       RETURNING *`,
      [name, company || null, phone, email || null, service, Number(expected_value) || 0]
    );

    res.status(201).json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Convert Lead -> Client
app.post('/api/leads/:id/convert', async (req, res) => {
  const client = await pool.connect();

  try {
    await client.query('BEGIN');

    const leadResult = await client.query(
      'SELECT * FROM leads WHERE id = $1',
      [req.params.id]
    );

    if (!leadResult.rows.length) {
      await client.query('ROLLBACK');
      return res.status(404).json({ error: 'Lead not found' });
    }

    const lead = leadResult.rows[0];

    const clientResult = await client.query(
      `INSERT INTO clients (name, company, phone, email)
       VALUES ($1, $2, $3, $4)
       RETURNING id`,
      [lead.name, lead.company, lead.phone, lead.email]
    );

    await client.query(
      `UPDATE leads SET status = 'WON' WHERE id = $1`,
      [req.params.id]
    );

    await client.query('COMMIT');

    res.json({ success: true, clientId: clientResult.rows[0].id });
  } catch (err) {
    await client.query('ROLLBACK');
    res.status(500).json({ error: err.message });
  } finally {
    client.release();
  }
});

// CLIENTS
app.get('/api/clients', async (req, res) => {
  try {
    const { rows } = await pool.query('SELECT * FROM clients ORDER BY id DESC');
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/clients', async (req, res) => {
  try {
    const { name, company, phone, email, gstin, state, state_code } = req.body;

    if (!name || !phone) {
      return res.status(400).json({ error: 'Name and phone are required.' });
    }

    const { rows } = await pool.query(
      `INSERT INTO clients (name, company, phone, email, gstin, state, state_code)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       RETURNING *`,
      [
        name,
        company || null,
        phone,
        email || null,
        gstin || null,
        state || 'Maharashtra',
        state_code || '27'
      ]
    );

    res.status(201).json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// PROJECTS
app.get('/api/projects', async (req, res) => {
  try {
    const { rows } = await pool.query('SELECT * FROM projects ORDER BY id DESC');
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/projects', async (req, res) => {
  try {
    const { title, client_name, service, budget, deadline } = req.body;

    if (!title || !client_name || !deadline) {
      return res.status(400).json({ error: 'Project, client and deadline are required.' });
    }

    const { rows } = await pool.query(
      `INSERT INTO projects (title, client_name, service, budget, deadline)
       VALUES ($1, $2, $3, $4, $5)
       RETURNING *`,
      [title, client_name, service || null, Number(budget) || 0, deadline]
    );

    res.status(201).json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// INVOICES & GST
app.get('/api/invoices', async (req, res) => {
  try {
    const { rows } = await pool.query('SELECT * FROM invoices ORDER BY id DESC');
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/invoices', async (req, res) => {
  try {
    const { client_name, taxable_amount, is_interstate } = req.body;
    const taxable = Number(taxable_amount) || 0;

    if (!client_name || taxable <= 0) {
      return res.status(400).json({ error: 'Client name and taxable amount are required.' });
    }

    const gstRate = 18;
    const totalTax = (taxable * gstRate) / 100;
    const grandTotal = taxable + totalTax;

    const prefix = 'INV-';
    const invoiceNumber = prefix + Date.now().toString().slice(-8);
    const today = new Date().toISOString().split('T')[0];

    const { rows } = await pool.query(
      `INSERT INTO invoices
       (invoice_number, client_name, taxable_amount, gst_rate, total_tax, grand_total, date)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       RETURNING *`,
      [invoiceNumber, client_name, taxable, gstRate, totalTax, grandTotal, today]
    );

    res.status(201).json(rows[0]);
  } catch (err) {
    if (err.code === '23505') {
      return res.status(409).json({ error: 'Invoice number already exists. Please try again.' });
    }
    res.status(500).json({ error: err.message });
  }
});

// Frontend fallback
app.get('*', (req, res) => {
  if (req.path.startsWith('/api/')) {
    return res.status(404).json({ error: 'API route not found' });
  }
  res.sendFile(path.join(__dirname, '..', 'client', 'index.html'));
});

initDatabase()
  .then(() => {
    app.listen(PORT, () => {
      console.log(`SYNICON CRM running on port ${PORT}`);
    });
  })
  .catch((err) => {
    console.error('Database initialization failed:', err);
    process.exit(1);
  });
